/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproyecto.Menu;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Actualizar extends javax.swing.JFrame {
    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg_3 = new javax.swing.JPanel();
        Panel_Ingreso = new javax.swing.JPanel();
        Multi_Panel = new javax.swing.JTabbedPane();
        Soldado_raso = new javax.swing.JPanel();
        NombreR = new javax.swing.JTextField();
        CodigoR = new javax.swing.JTextField();
        UnidadR = new javax.swing.JTextField();
        GuardarR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Teniente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreT = new javax.swing.JTextField();
        CodigoT = new javax.swing.JTextField();
        UnidadT = new javax.swing.JTextField();
        GuardarT = new javax.swing.JButton();
        Capitan = new javax.swing.JPanel();
        NombreCa = new javax.swing.JTextField();
        CodigoCa = new javax.swing.JTextField();
        UnidadCa = new javax.swing.JTextField();
        UnidadesCa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GuardarCa = new javax.swing.JButton();
        Coronel = new javax.swing.JPanel();
        NombreCo = new javax.swing.JTextField();
        CodigoCo = new javax.swing.JTextField();
        UnidadCo = new javax.swing.JTextField();
        EstrategiaCo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GuardarCo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg_3.setBackground(new java.awt.Color(133, 159, 61));
        Bg_3.setPreferredSize(new java.awt.Dimension(800, 500));
        Bg_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Ingreso.setPreferredSize(new java.awt.Dimension(800, 500));

        Multi_Panel.setBackground(new java.awt.Color(49, 81, 30));
        Multi_Panel.setForeground(new java.awt.Color(255, 255, 255));
        Multi_Panel.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        Multi_Panel.setPreferredSize(new java.awt.Dimension(64, 22));

        Soldado_raso.setBackground(new java.awt.Color(49, 81, 30));

        NombreR.setBackground(new java.awt.Color(26, 26, 25));
        NombreR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreR.setForeground(new java.awt.Color(255, 255, 255));

        CodigoR.setBackground(new java.awt.Color(26, 26, 25));
        CodigoR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoR.setForeground(new java.awt.Color(255, 255, 255));

        UnidadR.setBackground(new java.awt.Color(26, 26, 25));
        UnidadR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadR.setForeground(new java.awt.Color(255, 255, 255));

        GuardarR.setBackground(new java.awt.Color(15, 15, 15));
        GuardarR.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        GuardarR.setForeground(new java.awt.Color(255, 255, 255));
        GuardarR.setText("Guardar");
        GuardarR.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Unidad");

        javax.swing.GroupLayout Soldado_rasoLayout = new javax.swing.GroupLayout(Soldado_raso);
        Soldado_raso.setLayout(Soldado_rasoLayout);
        Soldado_rasoLayout.setHorizontalGroup(
            Soldado_rasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Soldado_rasoLayout.createSequentialGroup()
                .addGroup(Soldado_rasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Soldado_rasoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Soldado_rasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20)
                        .addGroup(Soldado_rasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CodigoR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(UnidadR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(NombreR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addGroup(Soldado_rasoLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(GuardarR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        Soldado_rasoLayout.setVerticalGroup(
            Soldado_rasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Soldado_rasoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Soldado_rasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(Soldado_rasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(Soldado_rasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(GuardarR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Multi_Panel.addTab("Raso", Soldado_raso);

        Teniente.setBackground(new java.awt.Color(49, 81, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Unidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Codigo");

        NombreT.setBackground(new java.awt.Color(26, 26, 25));
        NombreT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreT.setForeground(new java.awt.Color(255, 255, 255));

        CodigoT.setBackground(new java.awt.Color(26, 26, 25));
        CodigoT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoT.setForeground(new java.awt.Color(255, 255, 255));

        UnidadT.setBackground(new java.awt.Color(26, 26, 25));
        UnidadT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadT.setForeground(new java.awt.Color(255, 255, 255));

        GuardarT.setBackground(new java.awt.Color(15, 15, 15));
        GuardarT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        GuardarT.setForeground(new java.awt.Color(255, 255, 255));
        GuardarT.setText("Guardar");
        GuardarT.setBorder(null);

        javax.swing.GroupLayout TenienteLayout = new javax.swing.GroupLayout(Teniente);
        Teniente.setLayout(TenienteLayout);
        TenienteLayout.setHorizontalGroup(
            TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TenienteLayout.createSequentialGroup()
                .addGroup(TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TenienteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TenienteLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TenienteLayout.createSequentialGroup()
                                .addGroup(TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodigoT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UnidadT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(TenienteLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(GuardarT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        TenienteLayout.setVerticalGroup(
            TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TenienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(TenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UnidadT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(GuardarT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Multi_Panel.addTab("Ten", Teniente);

        Capitan.setBackground(new java.awt.Color(49, 81, 30));

        NombreCa.setEditable(false);
        NombreCa.setBackground(new java.awt.Color(26, 26, 25));
        NombreCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreCa.setForeground(new java.awt.Color(255, 255, 255));

        CodigoCa.setBackground(new java.awt.Color(26, 26, 25));
        CodigoCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoCa.setForeground(new java.awt.Color(255, 255, 255));

        UnidadCa.setBackground(new java.awt.Color(26, 26, 25));
        UnidadCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadCa.setForeground(new java.awt.Color(255, 255, 255));

        UnidadesCa.setBackground(new java.awt.Color(26, 26, 25));
        UnidadesCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadesCa.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Codigo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Unidad");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Unidades");

        GuardarCa.setBackground(new java.awt.Color(15, 15, 15));
        GuardarCa.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        GuardarCa.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCa.setText("Guardar");
        GuardarCa.setBorder(null);

        javax.swing.GroupLayout CapitanLayout = new javax.swing.GroupLayout(Capitan);
        Capitan.setLayout(CapitanLayout);
        CapitanLayout.setHorizontalGroup(
            CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CapitanLayout.createSequentialGroup()
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CapitanLayout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(UnidadCa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CodigoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UnidadesCa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(CapitanLayout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(GuardarCa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CapitanLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CapitanLayout.createSequentialGroup()
                                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(CapitanLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel10))
                                        .addComponent(jLabel9))
                                    .addGroup(CapitanLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(13, 13, 13)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CapitanLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(NombreCa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CapitanLayout.setVerticalGroup(
            CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CapitanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadCa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadesCa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(GuardarCa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Multi_Panel.addTab("Cap", Capitan);

        Coronel.setBackground(new java.awt.Color(49, 81, 30));

        NombreCo.setBackground(new java.awt.Color(26, 26, 25));
        NombreCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreCo.setForeground(new java.awt.Color(255, 255, 255));

        CodigoCo.setBackground(new java.awt.Color(26, 26, 25));
        CodigoCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoCo.setForeground(new java.awt.Color(255, 255, 255));

        UnidadCo.setBackground(new java.awt.Color(26, 26, 25));
        UnidadCo.setForeground(new java.awt.Color(255, 255, 255));

        EstrategiaCo.setBackground(new java.awt.Color(26, 26, 25));
        EstrategiaCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EstrategiaCo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Codigo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Unidad");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Estrategia");

        GuardarCo.setBackground(new java.awt.Color(15, 15, 15));
        GuardarCo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        GuardarCo.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCo.setText("Guardar");
        GuardarCo.setBorder(null);

        javax.swing.GroupLayout CoronelLayout = new javax.swing.GroupLayout(Coronel);
        Coronel.setLayout(CoronelLayout);
        CoronelLayout.setHorizontalGroup(
            CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoronelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CoronelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(20, 20, 20)
                        .addComponent(EstrategiaCo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CoronelLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(20, 20, 20)
                            .addComponent(NombreCo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CoronelLayout.createSequentialGroup()
                            .addGroup(CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CodigoCo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UnidadCo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(CoronelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(GuardarCo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CoronelLayout.setVerticalGroup(
            CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoronelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(20, 20, 20)
                .addGroup(CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoCo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(20, 20, 20)
                .addGroup(CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadCo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(20, 20, 20)
                .addGroup(CoronelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstrategiaCo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(GuardarCo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Multi_Panel.addTab("Cor", Coronel);

        jPanel1.setBackground(new java.awt.Color(49, 81, 30));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 64));
        jPanel1.setRequestFocusEnabled(false);

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Actualizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel15)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_IngresoLayout = new javax.swing.GroupLayout(Panel_Ingreso);
        Panel_Ingreso.setLayout(Panel_IngresoLayout);
        Panel_IngresoLayout.setHorizontalGroup(
            Panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IngresoLayout.createSequentialGroup()
                .addGroup(Panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_IngresoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_IngresoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Multi_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_IngresoLayout.setVerticalGroup(
            Panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_IngresoLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Multi_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Bg_3.add(Panel_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 20, 537, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getGuardarCa() {
        return GuardarCa;
    }

    public JButton getGuardarCo() {
        return GuardarCo;
    }

    public JButton getGuardarR() {
        return GuardarR;
    }

    public JButton getGuardarT() {
        return GuardarT;
    }

    public JTextField getNombreCa() {
        return NombreCa;
    }

    public JTextField getNombreCo() {
        return NombreCo;
    }

    public JTextField getNombreR() {
        return NombreR;
    }

    public JTextField getNombreT() {
        return NombreT;
    }

    public JTextField getUnidadCa() {
        return UnidadCa;
    }

    public JTextField getUnidadCo() {
        return UnidadCo;
    }

    public JTextField getUnidadR() {
        return UnidadR;
    }

    public JTextField getUnidadT() {
        return UnidadT;
    }

    public JTextField getUnidadesCa() {
        return UnidadesCa;
    }

    public JTextField getEstrategiaCo() {
        return EstrategiaCo;
    }

    public JTextField getCodigoCa() {
        return CodigoCa;
    }

    public JTextField getCodigoCo() {
        return CodigoCo;
    }

    public JTextField getCodigoR() {
        return CodigoR;
    }

    public JTextField getCodigoT() {
        return CodigoT;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg_3;
    private javax.swing.JPanel Capitan;
    private javax.swing.JTextField CodigoCa;
    private javax.swing.JTextField CodigoCo;
    private javax.swing.JTextField CodigoR;
    private javax.swing.JTextField CodigoT;
    private javax.swing.JPanel Coronel;
    private javax.swing.JTextField EstrategiaCo;
    private javax.swing.JButton GuardarCa;
    private javax.swing.JButton GuardarCo;
    private javax.swing.JButton GuardarR;
    private javax.swing.JButton GuardarT;
    private javax.swing.JTabbedPane Multi_Panel;
    private javax.swing.JTextField NombreCa;
    private javax.swing.JTextField NombreCo;
    private javax.swing.JTextField NombreR;
    private javax.swing.JTextField NombreT;
    private javax.swing.JPanel Panel_Ingreso;
    private javax.swing.JPanel Soldado_raso;
    private javax.swing.JPanel Teniente;
    private javax.swing.JTextField UnidadCa;
    private javax.swing.JTextField UnidadCo;
    private javax.swing.JTextField UnidadR;
    private javax.swing.JTextField UnidadT;
    private javax.swing.JTextField UnidadesCa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
