/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproyecto.Menu;

import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JTextPane;

import miniproyecto.app.Vista;

/**
 *
 * @author tsuna
 */
public class Consola extends javax.swing.JFrame {

    /**
     * Creates new form Consola
     */
    public Consola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg_3 = new javax.swing.JPanel();
        Input = new javax.swing.JTextField();
        GUITSelector = new javax.swing.JRadioButton();
        Terminal = new javax.swing.JLabel();
        Listado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg_3.setBackground(new java.awt.Color(133, 159, 61));
        Bg_3.setPreferredSize(new java.awt.Dimension(800, 500));
        Bg_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Input.setText("Ingrese entrada");
        Bg_3.add(Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 680, 30));

        GUITSelector.setText("GUI");
        Bg_3.add(GUITSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, -1));

        Terminal.setBackground(new java.awt.Color(255, 255, 255));
        Terminal.setForeground(new java.awt.Color(255, 255, 255));
        Terminal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Terminal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Terminal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bg_3.add(Terminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 450));
        Bg_3.add(Listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 250, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_3, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getTerminal() {
        return Terminal;
    }

    public JRadioButton getGUITSelector() {
        return GUITSelector;
    }

    public JTextField getInput() {
        return Input;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg_3;
    private javax.swing.JRadioButton GUITSelector;
    private javax.swing.JTextField Input;
    private javax.swing.JLabel Listado;
    private javax.swing.JLabel Terminal;
    // End of variables declaration//GEN-END:variables
}
