package miniproyecto.Menu;

import javax.swing.JButton;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Crear extends javax.swing.JFrame {

    /**
     * Creates new form Crear
     */
    public Crear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg_2 = new javax.swing.JPanel();
        Panel_botones = new javax.swing.JPanel();
        Soldado_Boton = new javax.swing.JButton();
        Teniente_Boton = new javax.swing.JButton();
        Capitan_Boton = new javax.swing.JButton();
        Coronel_Boton = new javax.swing.JButton();
        Texto = new javax.swing.JLabel();
        Volver_boton = new javax.swing.JButton();
        Panel_Ingreso = new javax.swing.JPanel();
        Multi_Panel = new javax.swing.JTabbedPane();
        Soldado_raso_crear = new javax.swing.JPanel();
        NombreR = new javax.swing.JTextField();
        CodigoR = new javax.swing.JTextField();
        UnidadR = new javax.swing.JTextField();
        GuardarR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Teniente_crear = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreT = new javax.swing.JTextField();
        CodigoT = new javax.swing.JTextField();
        UnidadT = new javax.swing.JTextField();
        GuardarT = new javax.swing.JButton();
        Capitan_crear = new javax.swing.JPanel();
        NombreCa = new javax.swing.JTextField();
        CodigoCa = new javax.swing.JTextField();
        UnidadCa = new javax.swing.JTextField();
        UnidadesCa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GuardarCa = new javax.swing.JButton();
        Coronel_crear = new javax.swing.JPanel();
        NombreCo = new javax.swing.JTextField();
        CodigoCo = new javax.swing.JTextField();
        UnidadCo = new javax.swing.JTextField();
        EstrategiaCo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GuardarCo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg_2.setBackground(new java.awt.Color(133, 159, 61));
        Bg_2.setMinimumSize(new java.awt.Dimension(800, 500));
        Bg_2.setPreferredSize(new java.awt.Dimension(800, 500));
        Bg_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_botones.setBackground(new java.awt.Color(26, 26, 25));
        Panel_botones.setForeground(new java.awt.Color(102, 102, 102));

        Soldado_Boton.setBackground(new java.awt.Color(15, 15, 15));
        Soldado_Boton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Soldado_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Soldado_Boton.setText("Soldado Raso");
        Soldado_Boton.setBorder(null);
        Soldado_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Soldado_BotonActionPerformed(evt);
            }
        });

        Teniente_Boton.setBackground(new java.awt.Color(15, 15, 15));
        Teniente_Boton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Teniente_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Teniente_Boton.setText("Teniente");
        Teniente_Boton.setBorder(null);
        Teniente_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teniente_BotonActionPerformed(evt);
            }
        });

        Capitan_Boton.setBackground(new java.awt.Color(15, 15, 15));
        Capitan_Boton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Capitan_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Capitan_Boton.setText("Capitan");
        Capitan_Boton.setBorder(null);
        Capitan_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Capitan_BotonActionPerformed(evt);
            }
        });

        Coronel_Boton.setBackground(new java.awt.Color(15, 15, 15));
        Coronel_Boton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Coronel_Boton.setForeground(new java.awt.Color(255, 255, 255));
        Coronel_Boton.setText("Coronel");
        Coronel_Boton.setBorder(null);
        Coronel_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Coronel_BotonActionPerformed(evt);
            }
        });

        Texto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Texto.setForeground(new java.awt.Color(255, 255, 255));
        Texto.setText("Seleccione:");

        Volver_boton.setBackground(new java.awt.Color(15, 15, 15));
        Volver_boton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Volver_boton.setForeground(new java.awt.Color(255, 255, 255));
        Volver_boton.setText("Volver");
        Volver_boton.setToolTipText("");
        Volver_boton.setBorder(null);

        javax.swing.GroupLayout Panel_botonesLayout = new javax.swing.GroupLayout(Panel_botones);
        Panel_botones.setLayout(Panel_botonesLayout);
        Panel_botonesLayout.setHorizontalGroup(
            Panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_botonesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(Panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto)
                    .addGroup(Panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Soldado_Boton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(Teniente_Boton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(Capitan_Boton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(Coronel_Boton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(Volver_boton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        Panel_botonesLayout.setVerticalGroup(
            Panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_botonesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Texto)
                .addGap(38, 38, 38)
                .addComponent(Soldado_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Teniente_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Capitan_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Coronel_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Volver_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Bg_2.add(Panel_botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 500));

        Panel_Ingreso.setPreferredSize(new java.awt.Dimension(800, 500));

        Multi_Panel.setBackground(new java.awt.Color(49, 81, 30));
        Multi_Panel.setForeground(new java.awt.Color(255, 255, 255));
        Multi_Panel.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        Multi_Panel.setPreferredSize(new java.awt.Dimension(64, 22));

        Soldado_raso_crear.setBackground(new java.awt.Color(49, 81, 30));

        NombreR.setBackground(new java.awt.Color(26, 26, 25));
        NombreR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreR.setForeground(new java.awt.Color(255, 255, 255));

        CodigoR.setBackground(new java.awt.Color(26, 26, 25));
        CodigoR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoR.setForeground(new java.awt.Color(255, 255, 255));

        UnidadR.setBackground(new java.awt.Color(26, 26, 25));
        UnidadR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadR.setForeground(new java.awt.Color(255, 255, 255));

        GuardarR.setBackground(new java.awt.Color(15, 15, 15));
        GuardarR.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        GuardarR.setForeground(new java.awt.Color(255, 255, 255));
        GuardarR.setText("Guardar");
        GuardarR.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Unidad");

        javax.swing.GroupLayout Soldado_raso_crearLayout = new javax.swing.GroupLayout(Soldado_raso_crear);
        Soldado_raso_crear.setLayout(Soldado_raso_crearLayout);
        Soldado_raso_crearLayout.setHorizontalGroup(
            Soldado_raso_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Soldado_raso_crearLayout.createSequentialGroup()
                .addGroup(Soldado_raso_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Soldado_raso_crearLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Soldado_raso_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20)
                        .addGroup(Soldado_raso_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CodigoR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(UnidadR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(NombreR, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addGroup(Soldado_raso_crearLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(GuardarR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Soldado_raso_crearLayout.setVerticalGroup(
            Soldado_raso_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Soldado_raso_crearLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(Soldado_raso_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(Soldado_raso_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(Soldado_raso_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(GuardarR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Multi_Panel.addTab("Raso", Soldado_raso_crear);

        Teniente_crear.setBackground(new java.awt.Color(49, 81, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Unidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Codigo");

        NombreT.setBackground(new java.awt.Color(26, 26, 25));
        NombreT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreT.setForeground(new java.awt.Color(255, 255, 255));

        CodigoT.setBackground(new java.awt.Color(26, 26, 25));
        CodigoT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoT.setForeground(new java.awt.Color(255, 255, 255));

        UnidadT.setBackground(new java.awt.Color(26, 26, 25));
        UnidadT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadT.setForeground(new java.awt.Color(255, 255, 255));

        GuardarT.setBackground(new java.awt.Color(15, 15, 15));
        GuardarT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        GuardarT.setForeground(new java.awt.Color(255, 255, 255));
        GuardarT.setText("Guardar");
        GuardarT.setBorder(null);

        javax.swing.GroupLayout Teniente_crearLayout = new javax.swing.GroupLayout(Teniente_crear);
        Teniente_crear.setLayout(Teniente_crearLayout);
        Teniente_crearLayout.setHorizontalGroup(
            Teniente_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Teniente_crearLayout.createSequentialGroup()
                .addGroup(Teniente_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Teniente_crearLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Teniente_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Teniente_crearLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CodigoT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Teniente_crearLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(20, 20, 20)
                                .addComponent(NombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Teniente_crearLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(UnidadT, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Teniente_crearLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(GuardarT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Teniente_crearLayout.setVerticalGroup(
            Teniente_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Teniente_crearLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Teniente_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Teniente_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(Teniente_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(GuardarT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Multi_Panel.addTab("Ten", Teniente_crear);

        Capitan_crear.setBackground(new java.awt.Color(49, 81, 30));

        NombreCa.setBackground(new java.awt.Color(26, 26, 25));
        NombreCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreCa.setForeground(new java.awt.Color(255, 255, 255));

        CodigoCa.setBackground(new java.awt.Color(26, 26, 25));
        CodigoCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoCa.setForeground(new java.awt.Color(255, 255, 255));

        UnidadCa.setBackground(new java.awt.Color(26, 26, 25));
        UnidadCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadCa.setForeground(new java.awt.Color(255, 255, 255));

        UnidadesCa.setBackground(new java.awt.Color(26, 26, 25));
        UnidadesCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadesCa.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Codigo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Unidad");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Unidades");

        GuardarCa.setBackground(new java.awt.Color(15, 15, 15));
        GuardarCa.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        GuardarCa.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCa.setText("Guardar");
        GuardarCa.setBorder(null);

        javax.swing.GroupLayout Capitan_crearLayout = new javax.swing.GroupLayout(Capitan_crear);
        Capitan_crear.setLayout(Capitan_crearLayout);
        Capitan_crearLayout.setHorizontalGroup(
            Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Capitan_crearLayout.createSequentialGroup()
                .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Capitan_crearLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(UnidadesCa, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Capitan_crearLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodigoCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UnidadCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Capitan_crearLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Capitan_crearLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(NombreCa, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Capitan_crearLayout.createSequentialGroup()
                                    .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGroup(Capitan_crearLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(13, 13, 13)))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(Capitan_crearLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(GuardarCa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        Capitan_crearLayout.setVerticalGroup(
            Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Capitan_crearLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadCa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(Capitan_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadesCa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(GuardarCa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Multi_Panel.addTab("Cap", Capitan_crear);

        Coronel_crear.setBackground(new java.awt.Color(49, 81, 30));

        NombreCo.setBackground(new java.awt.Color(26, 26, 25));
        NombreCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NombreCo.setForeground(new java.awt.Color(255, 255, 255));

        CodigoCo.setBackground(new java.awt.Color(26, 26, 25));
        CodigoCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoCo.setForeground(new java.awt.Color(255, 255, 255));

        UnidadCo.setBackground(new java.awt.Color(26, 26, 25));
        UnidadCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UnidadCo.setForeground(new java.awt.Color(255, 255, 255));

        EstrategiaCo.setBackground(new java.awt.Color(26, 26, 25));
        EstrategiaCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EstrategiaCo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Codigo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Unidad");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Estrategia");

        GuardarCo.setBackground(new java.awt.Color(15, 15, 15));
        GuardarCo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        GuardarCo.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCo.setText("Guardar");
        GuardarCo.setBorder(null);

        javax.swing.GroupLayout Coronel_crearLayout = new javax.swing.GroupLayout(Coronel_crear);
        Coronel_crear.setLayout(Coronel_crearLayout);
        Coronel_crearLayout.setHorizontalGroup(
            Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Coronel_crearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Coronel_crearLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(20, 20, 20)
                        .addComponent(EstrategiaCo, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(Coronel_crearLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(20, 20, 20)
                            .addComponent(NombreCo, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Coronel_crearLayout.createSequentialGroup()
                            .addGroup(Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CodigoCo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UnidadCo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(Coronel_crearLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(GuardarCo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Coronel_crearLayout.setVerticalGroup(
            Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Coronel_crearLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(20, 20, 20)
                .addGroup(Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoCo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(20, 20, 20)
                .addGroup(Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnidadCo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(20, 20, 20)
                .addGroup(Coronel_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstrategiaCo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(GuardarCo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Multi_Panel.addTab("Cor", Coronel_crear);

        javax.swing.GroupLayout Panel_IngresoLayout = new javax.swing.GroupLayout(Panel_Ingreso);
        Panel_Ingreso.setLayout(Panel_IngresoLayout);
        Panel_IngresoLayout.setHorizontalGroup(
            Panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Multi_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_IngresoLayout.setVerticalGroup(
            Panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Multi_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        Bg_2.add(Panel_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 510, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Coronel_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Coronel_BotonActionPerformed
        Multi_Panel.setSelectedIndex(3);
    }//GEN-LAST:event_Coronel_BotonActionPerformed

    private void Capitan_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Capitan_BotonActionPerformed
        Multi_Panel.setSelectedIndex(2);
    }//GEN-LAST:event_Capitan_BotonActionPerformed

    private void Teniente_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teniente_BotonActionPerformed
        Multi_Panel.setSelectedIndex(1);
    }//GEN-LAST:event_Teniente_BotonActionPerformed

    private void Soldado_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Soldado_BotonActionPerformed
        Multi_Panel.setSelectedIndex(0);
    }//GEN-LAST:event_Soldado_BotonActionPerformed

    public JButton getVolver_boton() {
        return Volver_boton;
    }

    public JButton getGuardarR() {
        return GuardarR;
    }

    public JButton getGuardarT() {
        return GuardarT;
    }

    public JButton getGuardarCa() {
        return GuardarCa;
    }

    public JButton getGuardarCo() {
        return GuardarCo;
    }

    public JTextField getNombreR() {
        return NombreR;
    }

    public JTextField getNombreT() {
        return NombreT;
    }

    public JTextField getNombreCa() {
        return NombreCa;
    }

    public JTextField getNombreCo() {
        return NombreCo;
    }

    public JTextField getCodigoR() {
        return CodigoR;
    }

    public JTextField getCodigoT() {
        return CodigoT;
    }

    public JTextField getCodigoCa() {
        return CodigoCa;
    }

    public JTextField getCodigoCo() {
        return CodigoCo;
    }

    public JTextField getUnidadR() {
        return UnidadR;
    }

    public JTextField getUnidadT() {
        return UnidadT;
    }

    public JTextField getUnidadCa() {
        return UnidadCa;
    }

    public JTextField getUnidadCo() {
        return UnidadCo;
    }

    public JTextField getUnidadesCa() {
        return UnidadesCa;
    }

    public JTextField getEstrategiaCo() {
        return EstrategiaCo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg_2;
    private javax.swing.JButton Capitan_Boton;
    private javax.swing.JPanel Capitan_crear;
    private javax.swing.JTextField CodigoCa;
    private javax.swing.JTextField CodigoCo;
    private javax.swing.JTextField CodigoR;
    private javax.swing.JTextField CodigoT;
    private javax.swing.JButton Coronel_Boton;
    private javax.swing.JPanel Coronel_crear;
    private javax.swing.JTextField EstrategiaCo;
    private javax.swing.JButton GuardarCa;
    private javax.swing.JButton GuardarCo;
    private javax.swing.JButton GuardarR;
    private javax.swing.JButton GuardarT;
    private javax.swing.JTabbedPane Multi_Panel;
    private javax.swing.JTextField NombreCa;
    private javax.swing.JTextField NombreCo;
    private javax.swing.JTextField NombreR;
    private javax.swing.JTextField NombreT;
    private javax.swing.JPanel Panel_Ingreso;
    private javax.swing.JPanel Panel_botones;
    private javax.swing.JButton Soldado_Boton;
    private javax.swing.JPanel Soldado_raso_crear;
    private javax.swing.JButton Teniente_Boton;
    private javax.swing.JPanel Teniente_crear;
    private javax.swing.JLabel Texto;
    private javax.swing.JTextField UnidadCa;
    private javax.swing.JTextField UnidadCo;
    private javax.swing.JTextField UnidadR;
    private javax.swing.JTextField UnidadT;
    private javax.swing.JTextField UnidadesCa;
    private javax.swing.JButton Volver_boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
